name: coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
          python-version: '3.6'
    - run:
          pip install sympy
          pip install coverage
          coverage xml system_L.py
          # pip install pytest
          # pip install pytest-cov
          # pytest --cov=./ --cov-report=xml
    - name: upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
          # token: ${{secrets.CODECOV_TOKEN}}  # required for private repos
          file: ./coverage.xml
